[package]
name = "central-sos-session-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
central-sos-link = { path = "../link" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Graphics_Printing", "Win32_System_Diagnostics_ToolHelp", "Win32_System_RemoteDesktop", "Win32_Security", "Win32_Foundation"] }
