import { Database } from 'lucide-react';
import { SupportService } from '../../services/support/SupportService';
import { correctKnownServices } from '../../services/support/SupportRepair';
import { interpretFirebird, serviceState } from '../../services/support/SupportInterpretation';
import type { FirebirdSnapshot } from '../../types/support';
import { SupportHeader, SupportFeedback, TechnicalDetails, useSupportTask, InstallationsLink, formatBytes } from './SupportUI';

export function FirebirdPage() {
  const task = useSupportTask<FirebirdSnapshot>(); const refresh = () => task.run(SupportService.firebird); const info = task.result ? interpretFirebird(task.result) : null;
  const repair = () => task.run(async () => { const before = await SupportService.firebird(); const messages = await correctKnownServices(SupportService, before.services.items); const after = await SupportService.firebird(); task.setMessage(messages.join(' ') || 'Nenhum serviço conhecido parado e habilitado exigiu correção.'); return after; });
  return <><SupportHeader title="Firebird" description="Instalações, serviços, processo, porta 3050 e metadados do AUTOCOM.FDB." icon={Database} busy={task.busy} action={refresh}/><SupportFeedback {...task}/>{task.result && info && <><section className="support-card"><h2>{info.installed ? '✓ Firebird encontrado' : info.installationUnknown ? '⚠ Instalação não confirmada' : '⚠ Firebird não encontrado nas fontes consultadas'}</h2>{task.result.installations.items.map((software,index) => <p key={index}>{software.name} · {software.version ?? 'Versão não informada'} · {software.architecture ?? 'Arquitetura não determinada'}</p>)}{task.result.services.items.map(s => <p key={s.name}>{s.displayName || s.name}: {serviceState(s)} · {s.startMode || 'Inicialização não informada'}</p>)}<p>TCP 3050: {task.result.port.tcp.state === 'success' ? '✓ Aceita conexão local' : task.result.port.listeners.length ? '⚠ Listener encontrado; teste TCP falhou' : '⚠ Conexão não confirmada'}</p>{info.conflicting.length > 0 && <p>⚠ Porta ocupada por outro processo: {info.conflicting.map(p => `${p.processName} (PID ${p.pid})`).join(', ')}. Nenhum processo será encerrado.</p>}{info.multipleInstallations && <p>⚠ Mais de um caminho de instalação/serviço encontrado; confira os detalhes.</p>}<div className="support-actions"><button className="primary" disabled={task.busy} onClick={repair}>Verificar e corrigir</button>{!info.installed && <InstallationsLink/>}</div><TechnicalDetails data={task.result}/></section><section className="support-card"><h2>Banco AUTOCOM</h2><p>{task.result.database.exists === true ? '✓ AUTOCOM.FDB encontrado' : task.result.database.exists === false ? '⚠ AUTOCOM.FDB não encontrado' : '⚠ Não foi possível determinar a existência/acesso'}</p><p>{task.result.database.path}</p>{task.result.database.exists && <><p>Tamanho: {formatBytes(task.result.database.sizeBytes)}</p><p>Modificado: {task.result.database.modifiedAt ? new Date(task.result.database.modifiedAt).toLocaleString() : 'Não informado'}</p></>}{(task.result.database.readAccess === false || task.result.database.writeAccess === false) && <p>⚠ Banco encontrado, mas com acesso insuficiente por ACL/atributos.</p>}<p>Permissões por ACL · Leitura: {task.result.database.readAccess == null ? 'Não verificada sem abrir o banco' : task.result.database.readAccess ? 'Permitida' : 'Negada'} · Escrita: {task.result.database.writeAccess == null ? 'Não verificada' : task.result.database.writeAccess ? 'Permitida' : 'Não permitida por ACL/atributos'} · Bloqueio: não verificado.</p><p>{task.result.database.error}</p></section></>}</>;
}
