import { SupportService } from '../../services/support/SupportService';
import { collectNetworkIssues } from '../../services/support/NetworkKnownIssues';
import { repairNetwork } from '../../services/support/SupportRepair';
import { selectPrimaryAdapter } from '../../services/network/NetworkDiagnostic';
import type { NetworkSupportSnapshot } from '../../types/support';
import { useSupportConfirmation, TechnicalDetails } from './SupportUI';

export function NetworkOperationsPanel({ snapshot, busy, operate }: { snapshot: NetworkSupportSnapshot; busy: boolean; operate: (operation: () => Promise<{ after: NetworkSupportSnapshot; message: string }>) => Promise<void> }) {
  const { confirm, dialog } = useSupportConfirmation(); const issues = collectNetworkIssues(snapshot); const primary = selectPrimaryAdapter(snapshot.adapters.items).adapter;
  const verify = () => operate(async () => { const result = await repairNetwork(SupportService, issue => confirm(`${issue.description} ${issue.suggestedAction} A conexão de suporte remoto pode ser interrompida.`)); return { after: result.after, message: result.messages.join(' ') || (result.remaining.length ? 'Verificação concluída. Os avisos restantes exigem análise; nenhum reset foi executado.' : 'Nenhum problema confirmado exigiu correção.') }; });
  const removeProxy = async (action: 'removeWininetProxy' | 'removeWinhttpProxy') => { if (!await confirm('Remover somente este proxy manual? Isso pode interromper aplicações e violar uma configuração necessária à rede. PAC, WPAD e configurações por aplicação serão preservados.')) return; await operate(async () => { const message = await SupportService.networkAction(action, null, true); return { after: await SupportService.network(), message }; }); };
  return <><section className="support-card"><h2>{primary ? `✓ ${primary.name} conectado` : '⚠ Conexão principal não determinada'}</h2>{primary && <p>{primary.ipv4.join(' · ')} · Gateway {primary.gateways.join(' · ') || 'Não informado'} · DNS {primary.dnsServers.join(' · ') || 'Não informado'}</p>}<p>Gateway: {snapshot.gateway?.ping.state === 'success' ? '✓ Resposta ICMP recebida' : 'Resposta não confirmada; ICMP pode ser bloqueado'}</p><p>DNS: {snapshot.external.dns.state === 'success' ? '✓ Windows resolveu github.com' : '⚠ Resolução externa não confirmada'}</p><p>Internet: {snapshot.external.tcp.state === 'success' ? '✓ github.com:443 aceita conexão' : '⚠ Teste externo não conectou; causa não determinada'}</p><button className="primary" disabled={busy} onClick={verify}>Verificar e corrigir</button>{issues.map((issue,index) => <div className="support-check warning" key={`${issue.id}-${index}`}><span>⚠ {issue.description}</span>{issue.id === 'PROXY_CONFIGURED' && (issue.action === 'removeWininetProxy' || issue.action === 'removeWinhttpProxy') && <button className="linkbtn" disabled={busy} onClick={() => removeProxy(issue.action as 'removeWininetProxy' | 'removeWinhttpProxy')}>Remover proxy</button>}</div>)}<TechnicalDetails data={{ probes: { gateway: snapshot.gateway, dns: snapshot.dnsServers, external: snapshot.external }, routes: snapshot.routes, proxies: snapshot.proxies, issues }}/></section>{dialog}</>;
}
