import { useState } from 'react';
import { Cpu } from 'lucide-react';
import { SupportService } from '../../services/support/SupportService';
import { knownProcessNames, processGroups } from '../../services/support/SupportInterpretation';
import type { ProcessInfo } from '../../types/support';
import type { SnapshotCollection } from '../../../packages/contracts/machine';
import { SupportHeader, SupportFeedback, TechnicalDetails, useSupportTask, useSupportConfirmation, formatBytes } from './SupportUI';
export function ProcessesPage() {
  const task = useSupportTask<SnapshotCollection<ProcessInfo>>(); const [query, setQuery] = useState(''); const [all, setAll] = useState(false); const { confirm, dialog } = useSupportConfirmation();
  const processes = task.result?.items ?? []; const visible = processes.filter(p => query.trim() ? `${p.name} ${p.pid} ${p.path ?? ''}`.toLowerCase().includes(query.trim().toLowerCase()) : all || knownProcessNames.has(p.name.toLowerCase())).sort((a,b) => a.name.localeCompare(b.name));
  const terminate = async (p: ProcessInfo) => { if (!await confirm(`Encerrar ${p.name} (PID ${p.pid})? Dados não salvos podem ser perdidos. O Windows revalidará identidade e proteção antes da ação.`)) return; await task.run(async () => { const message = await SupportService.terminate(p, true); const result = await SupportService.processes(); task.setMessage(message); return result; }); };
  return <><SupportHeader title="Processos" description="Prioridade para aplicações de suporte, com pesquisa por nome, PID ou caminho." icon={Cpu} busy={task.busy} action={() => task.run(SupportService.processes)}/><SupportFeedback {...task}/>{task.result && <><div className="support-form"><label>Pesquisar qualquer processo<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Nome, PID ou caminho"/></label><button className="linkbtn" onClick={() => setAll(!all)}>{all ? 'Somente conhecidos' : 'Mostrar todos'}</button></div>{processGroups(processes).filter(g => g.instances.length > 1).map(g => <p className="notice" key={g.name}>⚠ {g.name}: {g.instances.length} instâncias. Pode ser intencional; nenhuma será encerrada automaticamente.</p>)}<p>Ausência ou caminho inesperado só constituem problema quando houver requisito explícito configurado. CPU exige amostragem; não é inferida desta coleta.</p><section className="support-list">{visible.map(p => <article className="support-card" key={`${p.pid}-${p.startTime}`}><h2>{p.name} <small>PID {p.pid}</small></h2><p>Memória: {formatBytes(p.memoryBytes)} · Tempo: {(p.runtimeSeconds / 60).toFixed(0)} min · {p.user || 'Usuário não informado'}</p><button className="primary" disabled={task.busy || p.critical || p.startTime <= 0} onClick={() => terminate(p)}>{p.critical ? 'Processo protegido' : 'Encerrar processo'}</button><TechnicalDetails data={p}/></article>)}</section>{visible.length === 0 && <p className="notice">Nenhum processo corresponde ao filtro atual.</p>}</>}{dialog}</>;
}
