import { useState } from 'react';
import { FolderOpen } from 'lucide-react';
import { runtimeEnvironment } from '../../services/runtime/environment';
import { SupportService } from '../../services/support/SupportService';
import type { ShareInfo, ShareSnapshot } from '../../types/support';
import type { SnapshotCollection } from '../../types/machine';
import { CheckRow, SupportHeader, SupportFeedback, TechnicalDetails, useSupportTask } from './SupportUI';
export function SharesPage() {
  const [path, setPath] = useState(''); const [host, setHost] = useState(''); const task = useSupportTask<ShareSnapshot>(); const list = useSupportTask<SnapshotCollection<ShareInfo>>();
  const busy = task.busy || list.busy;
  return <><SupportHeader title="Compartilhamentos" description="Teste DNS, SMB e acesso ao caminho com as credenciais atuais do Windows." icon={FolderOpen} busy={busy}/><form className="support-form" onSubmit={e => { e.preventDefault(); void task.run(() => SupportService.share(path)); }}><label>Caminho UNC<input required value={path} onChange={e => setPath(e.target.value)} placeholder="\\SERVIDOR\Troia"/></label><button className="primary" disabled={busy || runtimeEnvironment !== 'desktop'}>Testar acesso</button></form><SupportFeedback {...task}/>{task.result && <section className="support-card"><h2>{task.result.path}</h2><CheckRow label="Servidor" check={task.result.connectivity.dns}/><CheckRow label="SMB · 445" check={task.result.connectivity.tcp}/><CheckRow label="Share" check={task.result.existence}/><CheckRow label="Acesso" check={task.result.access}/>{task.result.connectivity.tcp.state === 'success' && task.result.access.code === 5 && <p>O servidor está acessível, mas o Windows negou acesso ao compartilhamento.</p>}<TechnicalDetails data={task.result}/></section>}<form className="support-form" onSubmit={e => { e.preventDefault(); void list.run(() => SupportService.listShares(host)); }}><label>Servidor<input required value={host} onChange={e => setHost(e.target.value)} placeholder="SERVIDOR"/></label><button className="primary" disabled={busy || runtimeEnvironment !== 'desktop'}>Listar compartilhamentos</button></form><SupportFeedback error={list.error}/>{list.result && <section className="support-card"><h2>{list.result.items.length} compartilhamentos retornados pelo Windows</h2>{list.result.error && <p>{list.result.error}</p>}{list.result.items.map(share => <p key={share.path}><button className="linkbtn" onClick={() => setPath(share.path)}>{share.path}</button>{share.comment && <small> · {share.comment}</small>}</p>)}<p>Consulta somente ao servidor informado. Compartilhamentos administrativos ocultos não são apresentados.</p></section>}</>;
}
