import { Settings2 } from 'lucide-react';
import { SupportService } from '../../services/support/SupportService';
import { interpretSystem } from '../../services/support/SupportInterpretation';
import type { SystemSupportSnapshot } from '../../types/support';
import { SupportHeader, SupportFeedback, TechnicalDetails, useSupportTask, useSupportConfirmation, formatBytes } from './SupportUI';
export function SystemPage() {
  const task = useSupportTask<SystemSupportSnapshot>(); const { confirm, dialog } = useSupportConfirmation(); const refresh = () => task.run(SupportService.system); const info = task.result ? interpretSystem(task.result) : null;
  const clean = async () => { if (!await confirm('Remover somente arquivos .tmp/.temp com mais de 7 dias nas pastas temporárias oficiais? Diretórios, arquivos em uso e junctions serão preservados. A exclusão é permanente.')) return; await task.run(async () => { const r = await SupportService.cleanup(true); const next = await SupportService.system(); task.setMessage(`${formatBytes(r.removedBytes)} removidos em ${r.removedFiles} arquivos; ${r.skippedFiles} preservados; ${r.failures} raízes indisponíveis.`); return next; }); };
  const sync = async () => { if (!await confirm('Solicitar sincronização ao Windows Time? Pode ajustar o relógio e iniciar o serviço se estiver parado; timezone e fontes NTP serão preservados.')) return; await task.run(async () => { const result = await SupportService.syncTime(true); const next = await SupportService.system(); task.setMessage(result.state === 'success' ? 'Windows Time informa sincronização.' : 'Solicitação concluída; consulte os detalhes do Windows Time.'); return next; }); };
  return <><SupportHeader title="Sistema" description="Disco, reinicialização pendente, horário e temporários seguros." icon={Settings2} busy={task.busy} action={refresh}/><SupportFeedback {...task}/>{task.result && info && <><div className="support-cards"><section className="support-card"><h2>Disco</h2>{task.result.volumes.items.map(v => <p key={v.unit}>{v.unit} · {v.freeBytes == null ? '⚠ Espaço não informado' : `${info.lowSpace.includes(v) ? '⚠ Pouco espaço' : '✓'} ${formatBytes(v.freeBytes)} livres`}</p>)}{task.result.volumes.error && <p>{task.result.volumes.error}</p>}<p>Alerta operacional: menos de 2 GB ou de 5% livres.</p></section><section className="support-card"><h2>Reinicialização</h2><p>{info.rebootPending ? '⚠ Pendente' : task.result.rebootError ? 'Não confirmada' : '✓ Nenhum dos indicadores consultados está pendente'}</p><p>Ligado há {(task.result.uptimeSeconds / 3600).toFixed(1)} horas.</p></section><section className="support-card"><h2>Horário</h2><p>{new Date().toLocaleString()} · {task.result.timezone ?? 'Timezone não informado'}</p><p>{info.timeStopped ? '⚠ Windows Time parado' : task.result.timeSync.state === 'success' ? '✓ Windows Time informa sincronização' : '⚠ Sincronização não confirmada'}</p><button className="primary" disabled={task.busy} onClick={sync}>Sincronizar horário</button></section><section className="support-card"><h2>Temporários</h2><p>{formatBytes(task.result.temporary.reduce((bytes, temp) => bytes + temp.scannedBytes, 0))} encontrados na amostragem de metadados.</p><p>{formatBytes(info.tempBytes)} elegíveis para limpeza conservadora.</p><p>Somente .tmp/.temp com mais de 7 dias. Estimativa limitada a 10 mil entradas e 4 níveis por pasta.</p><button className="primary" disabled={task.busy || info.tempBytes === 0} onClick={clean}>Limpar arquivos temporários</button></section></div><TechnicalDetails data={task.result}/></>}{dialog}</>;
}
