import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Activity, ArrowRight, Box, Check, CircleAlert, Download, Monitor, Printer, Server, Settings2, ShieldCheck, Wifi } from 'lucide-react';
import { LocalConfigService } from '../services/runtime/localConfig';
import { runtimeEnvironment } from '../services/runtime/environment';
import { getComputerNetworkSummaryAdapters } from '../services/network/ComputerNetworkSummary';
import { groupValidationResults } from '../services/validation/ValidationRegistry';
import { runMachineValidation } from '../services/validation/runMachineValidation';
import { toolRegistry } from '../tools/registry';
import { getLatestWindowsRelease, type WindowsReleaseLookup } from '../services/releases/GitHubReleaseService';
import type { MachineEnvironment, MachineRole } from '../types';
import type { MachineValidationRun, ValidationCategory, ValidationStatus } from '../services/validation/types';
import { InstallationsPage as InstallationsCatalogPage } from './InstallationsPage';
import { ComputerDiagnosticPage } from './ComputerDiagnosticPage';
import '../snapshot.css';
import '../release-download.css';
function Heading({tag,title,description}:{tag:string;title:string;description:string}){return <div className="heading"><small>{tag}</small><h1>{title}</h1><p>{description}</p></div>}
const categoryLabels:Record<ValidationCategory,string>={system:'Sistema',network:'Rede',sharing:'Compartilhamento',files:'Arquivos / DLL',printers:'Impressão',storage:'Armazenamento',database:'Banco',firebird:'Firebird',backup:'Backup',ibconsole:'IBConsole',cloud_accounting:'Nuvem Contábil'};
const validationCategoryOrder:ValidationCategory[]=['system','network','sharing','files','printers','storage','database','firebird','backup','ibconsole','cloud_accounting'];
const statusLabels:Record<ValidationStatus,string>={success:'OK',warning:'Atenção',error:'Problema',skipped:'Ignorada',ignored:'Ignorada'};
const overallLabels={operational:'Operacional',attention:'Atenção',action_required:'Ação necessária'} as const;
function ValidationCounts({run}:{run:MachineValidationRun}){const {summary}=run;return <div className={`validation-summary ${summary.overallStatus}`}><div><small>Perfil aplicado: {run.profile}</small><b>Estado geral: {overallLabels[summary.overallStatus]}</b></div><span>{summary.total} verificações</span><span className="success-text">✓ {summary.success} OK</span><span className="warning-text">⚠ {summary.warning} alertas</span><span className="error-text">✗ {summary.error} problemas</span><span className="muted-text">— {summary.skipped} ignoradas</span></div>}
function EnvironmentForm({initial,onSave}:{initial:MachineEnvironment|null;onSave:(v:MachineEnvironment)=>void}){const [company,setCompany]=useState(initial?.companyName??'');const [name,setName]=useState(initial?.machineName??'');const [role,setRole]=useState<MachineRole>(initial?.machineRole??'terminal');return <form className="panel form" onSubmit={(e:FormEvent)=>{e.preventDefault();const v={companyName:company.trim(),machineName:name.trim(),machineRole:role};LocalConfigService.save(v);onSave(v)}}><h2>{initial?'Editar ambiente':'Configuração do ambiente'}</h2><small>Configuração salva localmente neste dispositivo.</small><label>Empresa<input required value={company} onChange={e=>setCompany(e.target.value)} placeholder="Nome da empresa"/></label><label>Nome da máquina<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: TERMINAL-03"/></label><label>Tipo da máquina</label><div className="roles">{(['terminal','server'] as const).map(x=><button type="button" className={role===x?'selected':''} onClick={()=>setRole(x)} key={x}>{x==='terminal'?<Monitor/>:<Server/>}{x==='terminal'?'Terminal':'Servidor'}{role===x&&<Check size={14}/>}</button>)}</div><button className="primary">Salvar configuração</button></form>}
export function Dashboard(){
  const [env,setEnv]=useState(LocalConfigService.load());
  const [editing,setEditing]=useState(false);
  const [validation,setValidation]=useState<MachineValidationRun|null>(null);
  const [validationError,setValidationError]=useState('');
  const [validating,setValidating]=useState(false);
  const runValidation=async()=>{setValidating(true);setValidationError('');try{setValidation(await runMachineValidation())}catch(e){setValidation(null);setValidationError(e instanceof Error?e.message:'Falha ao executar a validação.')}finally{setValidating(false)}};
  const hostname=validation?.snapshot.system.hostname;
  return <><Heading tag="VISÃO GERAL" title="Dashboard" description="Visão central do ambiente de suporte."/><div className="welcome"><Activity/><div><b>Bem-vindo à CENTRAL SOS</b><p>Ferramentas de suporte técnico em um só lugar.</p></div><span>{runtimeEnvironment.toUpperCase()}</span></div><h2 className="section">Ambiente da máquina</h2>{env&&!editing?<><div className="machine"><Monitor/><div><small>{env.companyName}</small><b>{env.machineName}</b><small>Perfil: {env.machineRole.toUpperCase()}{hostname?` · Host: ${hostname}`:''}</small></div><span>● Não verificado</span><button className="linkbtn" onClick={()=>setEditing(true)}>Editar</button></div><div className="grid">{[[Monitor,'Sistema'],[Wifi,'Rede'],[Printer,'Impressoras'],[Settings2,'Serviços'],[Box,'Aplicações']].map(([I,n]:any)=><div className="tile" key={n}><I/>{n}<small>Não verificado</small></div>)}</div></>:<EnvironmentForm initial={env} onSave={value=>{setEnv(value);setEditing(false)}}/>}<h2 className="section">Validação</h2><div className="validation-launch"><div><b>Estado da máquina conforme o perfil configurado</b><small>A validação usa o perfil como conjunto de regras esperado.</small></div><button className="primary" disabled={validating||runtimeEnvironment!=='desktop'} onClick={runValidation}>{validating?'Executando…':validation?'Executar novamente':'Executar validação'}</button></div>{validationError&&<p className="error">{validationError}</p>}{validation&&<><ValidationCounts run={validation}/><Link className="linkbtn" to="/validation">Ver resultados detalhados <ArrowRight size={14}/></Link></>}<h2 className="section">Acesso rápido</h2><Link className="tool" to="/tools/computer-diagnostic"><Activity/> Diagnóstico do Computador <ArrowRight/></Link></>}
export function ToolsPage(){const icons:Record<string,typeof Activity>={'computer-diagnostic':Monitor,'network-diagnostic':Wifi,'windows-services-diagnostic':Settings2};return <><Heading tag="CATÁLOGO" title="Ferramentas" description="Ferramentas disponíveis neste ambiente."/><div className="panel">{toolRegistry.map(t=>{const Icon=icons[t.id]??Activity;return <Link className="tool" key={t.id} to={t.path}><Icon/><div><b>{t.name}</b><small>{t.description}</small></div><span>{t.availableOn.includes(runtimeEnvironment)?'Disponível':'Exige Desktop'}</span><ArrowRight/></Link>})}</div></>}
export function DiagnosticPage(){return <ComputerDiagnosticPage getNetworkSummary={getComputerNetworkSummaryAdapters}/>}
export function ValidationPage(){
  const [validation,setValidation]=useState<MachineValidationRun|null>(null);
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const run=async()=>{setBusy(true);setError('');try{setValidation(await runMachineValidation())}catch(e){setValidation(null);setError(e instanceof Error?e.message:'Falha ao executar a validação.')}finally{setBusy(false)}};
  const groups=validation?groupValidationResults(validation.results):null;
  return <><Heading tag="CONFORMIDADE" title="Validação" description="Verificações somente leitura selecionadas pelo perfil configurado."/><div className="validation-toolbar"><span>{validation?`${validation.summary.total} verificações · Perfil ${validation.profile==='server'?'Servidor':'Terminal'}`:'A coleta é executada somente quando você solicitar.'}</span><button className="primary" disabled={busy||runtimeEnvironment!=='desktop'} onClick={run}>{busy?'Coletando e validando…':validation?'Executar novamente':'Executar validação'}</button></div><p className="snapshot-note">{validation?.profile==='server'?'Servidor inclui as verificações compartilhadas e o baseline de Terminal, além das regras específicas de Servidor.':'Terminal executa as verificações gerais e o baseline de Terminal.'}</p>{runtimeEnvironment==='web'&&<p className="notice"><Monitor/> As verificações do Windows exigem o aplicativo Desktop.</p>}{error&&<p className="error">{error}</p>}{validation&&<><ValidationCounts run={validation}/><div className="validation-groups">{validationCategoryOrder.map(category=>groups?.[category].length? <section className="panel validation-group" key={category}><h2>{categoryLabels[category]}</h2>{groups[category].map(result=><article className={`validation-result ${result.status}`} key={result.ruleId}><div className="validation-result-heading"><span className={`validation-icon ${result.status}`}>{result.status==='success'?'✓':result.status==='warning'?'⚠':result.status==='error'?'✗':'—'}</span><b>{result.title}</b><span className={`validation-status ${result.status}`}>{statusLabels[result.status]}</span></div><p>{result.description}</p>{(result.expected||result.actual)&&<small>Esperado: {result.expected||'—'} · Encontrado: {result.actual||'—'}</small>}{result.suggestedAction&&<small className="suggested-action">Nota: {result.suggestedAction}</small>}</article>)}</section>:null)}</div></>}</>}
export function InstallationsPage(){
  return <InstallationsCatalogPage/>;
}
export function FavoritesPage(){return <><Heading tag="ATALHOS" title="Favoritos" description="Acesse rapidamente suas ferramentas favoritas."/><div className="empty"><b>Nenhum favorito ainda</b><Link to="/tools">Explorar ferramentas</Link></div></>}
export function SupportPage(){return <><Heading tag="ATENDIMENTO" title="Suporte" description="Área reservada para acesso assistido futuro."/><p className="notice"><ShieldCheck/> Demonstração visual. Nenhuma autenticação real está disponível.</p><div className="panel form"><h2>Acesso de suporte</h2><label>Técnico<select disabled><option>Disponível futuramente</option></select></label><label>Código de confirmação<input disabled placeholder="Código do técnico"/></label><label><input type="checkbox" disabled/> Confiar neste dispositivo por 1 dia</label><button className="primary" disabled>Continuar</button><small>Mock local declarado; sem login real.</small></div></>}
export function SettingsPage(){const [env,setEnv]=useState(LocalConfigService.load());return <><Heading tag="PREFERÊNCIAS" title="Configurações" description="Perfil local, editável posteriormente."/><EnvironmentForm initial={env} onSave={setEnv}/></>}
export function DownloadPage(){
  const [release,setRelease]=useState<WindowsReleaseLookup|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState(false);
  const load=async(refresh=false)=>{
    setLoading(true);setError(false);
    try{setRelease(await getLatestWindowsRelease({refresh}))}catch{setRelease(null);setError(true)}finally{setLoading(false)}
  };
  useEffect(()=>{void load()},[]);
  const availableRelease=release?.status==='available'?release:null;
  const asset=availableRelease?.asset??null;
  const formatSize=(bytes:number|null)=>bytes===null?'':bytes<1024*1024?`${(bytes/1024).toLocaleString('pt-BR',{maximumFractionDigits:0})} KB`:`${(bytes/1024/1024).toLocaleString('pt-BR',{maximumFractionDigits:1})} MB`;
  const publishedAt=release?.status==='available'&&release.publishedAt?new Date(release.publishedAt).toLocaleDateString('pt-BR'):null;
  return <><Heading tag="APLICATIVO WINDOWS" title="Download" description="Versão Desktop da CENTRAL SOS."/><section className="panel release-card"><div className="release-icon"><Download/></div><div className="release-content"><b>CENTRAL SOS para Windows</b>{loading?<p>Consultando última versão…</p>:error?<><p>Não foi possível consultar a versão disponível.</p><button className="linkbtn" onClick={()=>void load(true)}>Tentar novamente</button></>:availableRelease?<><p>{availableRelease.version?`Versão ${availableRelease.version}`:'Versão não informada'}{publishedAt?` · Publicado em ${publishedAt}`:''}</p><small>{availableRelease.asset.name}{availableRelease.asset.sizeBytes!==null?` · ${formatSize(availableRelease.asset.sizeBytes)}`:''}</small></>:release?.status==='ambiguous-release'?<p>Há Releases do aplicativo com a mesma maior versão. Não foi possível determinar qual instalador usar.</p>:release?.status==='ambiguous'?<p>Há mais de um instalador possível nesta release. Não foi possível determinar o arquivo correto.</p>:release?.status==='no-installer'?<p>Instalador ainda não publicado.</p>:<><p>Nenhuma versão publicada</p><p>O instalador do CENTRAL SOS estará disponível aqui quando uma Release for publicada.</p></>}</div><div className="release-actions">{asset?<a className="primary" href={asset.downloadUrl} target="_blank" rel="noopener noreferrer" download>Baixar para Windows</a>:<button className="primary" disabled>Indisponível</button>}{!loading&&!error&&<button className="linkbtn" onClick={()=>void load(true)}>Atualizar</button>}</div></section>{error&&<p className="error"><CircleAlert/> A consulta ao GitHub falhou. Verifique a conexão e tente novamente.</p>}</>;
}
