import test from 'node:test';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
async function load(entry){const r=await build({entryPoints:[fileURLToPath(new URL(entry,import.meta.url))],bundle:true,platform:'node',format:'esm',write:false,jsx:'automatic',plugins:[{name:'shared-react',setup(b){b.onResolve({filter:/^react(?:\/.*)?$/},args=>({path:import.meta.resolve(args.path),external:true}));}}]});return import(`data:text/javascript;base64,${Buffer.from(r.outputFiles[0].contents).toString('base64')}`);}
const {runPrinterAutoFix,automaticRepairPlan,knownPrinterProblems,canRepairSupportPermissions,shouldRestartSpooler}=await load('../PrinterAutoFix.ts');
const {PrinterDiagnosticsPanel}=await load('../../../pages/PrinterDiagnosticsPanel.tsx');
const {createPrinterActionClient}=await load('../PrinterActionClient.ts');
const col=(items=[],error=null)=>({items,error});
const port=name=>({name,monitor:'Local',description:null,portType:1});
const serial=id=>({deviceId:id,name:'USB Serial',description:null,pnpDeviceId:'USB\\VID_1234&PID_ABCD',status:'OK',configManagerErrorCode:0});
const devices=ids=>({com:col(ids.map(id=>({portName:id,friendlyName:'USB Serial',instanceId:'USB\\VID_1234&PID_ABCD',statusFlags:0,configManagerErrorCode:0,queryError:null}))),usb:col()});
const snapshot=()=>({printer:{name:'Test',port:'COM3',driver:'Driver',server:null,shareName:null,attributes:0,statusBits:0,jobCount:0},printerError:null,queue:col(),ports:col([port('COM3')]),serial:col([serial('COM3')]),presentDevices:devices(['COM3']),tcp:col(),driver:{name:'Driver',environment:'Windows x64',version:'1.2',hardwareId:'USBPRINT\\VID_1234&PID_ABCD',provider:'Test'},driverError:null,spooler:{state:4,startMode:2,error:null},isElevated:true});
const job=(id,bits)=>({jobId:id,statusBits:bits,document:'Dummy',user:'Test',status:'Aguardando',statusDetail:null,sizeBytes:10,totalPages:null,pagesPrinted:null,submittedAt:'2000-01-01',position:1});
const acl=()=>({state:'available',notice:null,entries:[{sid:'S-1-1-0',account:'Todos',aceIndex:0,accessType:'Permitir',inherited:false,specialPermissions:false,editable:true,permissions:{print:true,managePrinter:false,manageDocuments:false}}]});
function harness(s=snapshot()) {
  const calls=[];let reads=0;let settles=0;
  const client={
    getDiagnostic:async()=>{reads++;return structuredClone(s);},
    startSpooler:async()=>{calls.push('start');s.spooler.state=4;return {before:{state:1},after:s.spooler,removedFiles:0,failedFiles:[]};},
    restartSpooler:async()=>{calls.push('restart');s.spooler.state=4;return {before:{state:7},after:s.spooler,removedFiles:0,failedFiles:[]};},
    resume:async()=>{calls.push('resume');s.printer.statusBits&=~1;},
    cancelProblemJob:async(_,id)=>{calls.push('cancel:'+id);s.queue.items=s.queue.items.filter(j=>j.jobId!==id);return true;},
    getPermissions:async()=>{calls.push('aclRead');return acl();},
    configurePermissions:async()=>{calls.push('baselineACL');},
    clearQueue:async()=>assert.fail('Automatic fix must never clear the whole queue'),
    resetSpooler:async()=>assert.fail('Automatic fix must never delete global spool files'),
    setPort:async()=>assert.fail('Automatic fix must never change a port'),
  };
  return {s,client,calls,get reads(){return reads;},get settles(){return settles;},run:(options={})=>runPrinterAutoFix(client,'Test',{settle:async()=>{settles++;},...options})};
}
test('apenas pausada: somente retoma, estabiliza e diagnostica novamente',async()=>{const h=harness();h.s.printer.statusBits=1;assert.deepEqual(automaticRepairPlan(h.s,'Test'),['resume']);const result=await h.run();assert.deepEqual(h.calls,['resume']);assert.equal(result.status,'corrected');assert.match(result.message,/retomada/);assert.ok(h.reads>=3);assert.ok(h.settles>0);assert.match(result.steps[0].before,/"statusBits":1/);assert.match(result.steps[0].after,/"statusBits":0/);});
test('spooler parado é iniciado, sem restart ou limpeza; outras regras são reavaliadas',async()=>{const h=harness();h.s.spooler.state=1;const result=await h.run();assert.deepEqual(h.calls,['start']);assert.equal(result.status,'corrected');assert.equal(result.snapshot.spooler.state,4);});
test('spooler parado sem elevação ou desabilitado não é alterado',async()=>{for(const kind of ['permission','disabled']){const h=harness();h.s.spooler.state=1;if(kind==='permission')h.s.isElevated=false;else h.s.spooler.startMode=4;const result=await h.run();assert.deepEqual(h.calls,[]);assert.equal(result.status,'failed');if(kind==='permission')assert.match(result.message,/administrador/);}});
test('job bloqueado é cancelado, fila saudável preservada e Spooler saudável não reinicia',async()=>{const h=harness();h.s.queue.items=[job(1,0x200),job(2,0),job(3,0x10),job(4,1)];const result=await h.run();assert.deepEqual(h.calls,['cancel:1']);assert.deepEqual(result.snapshot.queue.items.map(j=>j.jobId),[2,3,4]);assert.equal(result.removedJobs,1);assert.equal(result.status,'corrected');});
test('somente erro e bloqueio de driver são cancelados; papel/offline/intervenção são preservados',async()=>{const h=harness();h.s.queue.items=[job(1,2),job(2,0x200),job(3,0),job(4,0x10),job(5,0)];const result=await h.run();assert.deepEqual(h.calls,['cancel:1','cancel:2']);assert.equal(result.removedJobs,2);assert.equal(result.status,'corrected');});
test('fila normal, idade, status desconhecido e jobs já em exclusão não causam ações',async()=>{const h=harness();h.s.queue.items=[job(1,0),job(2,2|4),job(3,2|0x1000),job(4,undefined)];const result=await h.run();assert.deepEqual(h.calls,[]);assert.equal(result.status,'no_change');assert.equal(result.steps.length,0);});
test('porta incorreta fica pendente; candidatura única nunca altera porta automaticamente',async()=>{const h=harness();h.s.ports=col([port('COM4')]);h.s.serial=col([serial('COM4')]);const result=await h.run();assert.deepEqual(h.calls,[]);assert.equal(result.status,'failed');assert.equal(result.snapshot.printer.port,'COM3');assert.match(result.message,/porta/);});
test('porta ambígua não é escolhida nem corrigida automaticamente',async()=>{const h=harness();h.s.ports=col([port('COM4'),port('COM5')]);h.s.serial=col([serial('COM4'),serial('COM5')]);const result=await h.run();assert.deepEqual(h.calls,[]);assert.equal(result.snapshot.printer.port,'COM3');assert.equal(result.status,'failed');});
test('combinação de problemas aplica somente start, resume e cancelamento dirigido',async()=>{const h=harness();h.s.spooler.state=1;h.s.printer.statusBits=1;h.s.queue.items=[job(1,2),job(2,0)];const result=await h.run();assert.deepEqual(h.calls,['start','resume','cancel:1']);assert.equal(result.status,'corrected');assert.equal(result.steps.length,3);});
test('hardware offline permanece pendente e não dispara cancelamento automático',async()=>{const h=harness();h.s.printer.statusBits=0x80;h.s.queue.items=[job(1,0x20)];const result=await h.run();assert.deepEqual(h.calls,[]);assert.equal(result.status,'failed');assert.equal(result.title,'Intervenção necessária');assert.match(result.message,/Offline/);assert.equal(result.snapshot.printer.statusBits,0x80);});
test('falha em job não impede os outros e não dispara restart por acesso negado',async()=>{const h=harness();h.s.queue.items=[job(1,2),job(2,2)];h.client.cancelProblemJob=async(_,id)=>{h.calls.push('cancel:'+id);if(id===1)throw new Error('erro Windows 5');h.s.queue.items=h.s.queue.items.filter(j=>j.jobId!==id);return true;};h.client.getPermissions=async()=>({state:'unavailable',entries:[],notice:'ACL não verificável'});const result=await h.run();assert.deepEqual(h.calls,['cancel:1','cancel:2']);assert.equal(result.status,'partial');assert.equal(result.removedJobs,1);assert.ok(result.steps.some(s=>!s.success));});
test('serviço pausado confirmado permite restart após cancelamento; running + jobs persistentes não basta',async()=>{const h=harness();h.s.spooler.state=7;h.s.queue.items=[job(1,0x200)];h.client.cancelProblemJob=async()=>{h.calls.push('cancel:1');return true;};assert.equal(shouldRestartSpooler(h.s,'Test'),true);const result=await h.run();assert.deepEqual(h.calls,['cancel:1','restart']);assert.equal(result.status,'partial');const normal=harness();normal.s.queue.items=[job(1,0x200)];normal.client.cancelProblemJob=async()=>{normal.calls.push('cancel:1');return true;};assert.equal(shouldRestartSpooler(normal.s,'Test'),false);await normal.run();assert.deepEqual(normal.calls,['cancel:1']);});
test('printer pausada não implica Spooler pausado; falha de resume não reinicia serviço',async()=>{const h=harness();h.s.printer.statusBits=1;h.client.resume=async()=>{h.calls.push('resume');throw new Error('Operation failed');};const result=await h.run();assert.deepEqual(h.calls,['resume']);assert.equal(result.status,'failed');assert.ok(result.steps[0].nativeError);});
test('fila remota não reinicia/inicia o Spooler local nem o considera falha do servidor',async()=>{const h=harness();h.s.printer.server='\\\\SERVER';h.s.spooler.state=1;const result=await h.run();assert.deepEqual(h.calls,[]);assert.equal(result.status,'no_change');});
test('falha de start interrompe correções dependentes, e diagnóstico indisponível não inventa estado',async()=>{const h=harness();h.s.spooler.state=1;h.s.printer.statusBits=1;h.client.startSpooler=async()=>{h.calls.push('start');throw new Error('SCM denied');};const result=await h.run();assert.deepEqual(h.calls,['start']);assert.equal(result.status,'failed');const empty=harness();empty.client.getDiagnostic=async()=>{throw new Error('read failed');};const failed=await empty.run();assert.deepEqual(empty.calls,[]);assert.equal(failed.snapshot,null);assert.equal(failed.steps[0].action,'diagnose');});
test('estado observado após correção decide resultado, não só sucesso do comando',async()=>{const h=harness();h.s.printer.statusBits=1;h.client.resume=async()=>{h.calls.push('resume');};const result=await h.run();assert.equal(result.status,'failed');assert.equal(result.steps[0].success,false);assert.ok(h.reads>=4);});
test('job que se recuperou é preservado pela revalidação nativa e não conta como removido',async()=>{const h=harness();h.s.queue.items=[job(1,2)];h.client.cancelProblemJob=async()=>{h.s.queue.items[0].statusBits=0;return false;};const result=await h.run();assert.equal(result.removedJobs,0);assert.equal(result.status,'corrected');assert.equal(result.snapshot.queue.items.length,1);});
test('baseline de Todos só é reaplicado com negação real e ACL simples comprovadamente divergente',async()=>{const h=harness();h.s.printer.statusBits=1;let first=true;h.client.resume=async()=>{h.calls.push('resume');if(first){first=false;throw 'O Windows negou acesso à impressora.';}h.s.printer.statusBits=0;};const result=await h.run();assert.deepEqual(h.calls,['resume','aclRead','baselineACL','aclRead','resume']);assert.equal(result.status,'corrected');assert.ok(result.steps.some(s=>s.action==='supportPermissions'));const normal=harness();normal.s.printer.statusBits=1;await normal.run();assert.deepEqual(normal.calls,['resume']);});
test('ACL negada, herdada, especial, baseline ausente ou sem elevação não autoriza reaplicação',()=>{const s=snapshot();assert.equal(canRepairSupportPermissions(s,acl(),'managePrinter','Test'),true);for(const change of [a=>a.entries[0].accessType='Negar',a=>a.entries[0].inherited=true,a=>a.entries[0].specialPermissions=true,a=>a.entries=[],a=>a.state='unavailable']){const a=acl();change(a);assert.equal(canRepairSupportPermissions(s,a,'managePrinter','Test'),false);}s.isElevated=false;assert.equal(canRepairSupportPermissions(s,acl(),'managePrinter','Test'),false);});
test('command de auto-cancelamento é dedicado e não recebe script nem ações genéricas',async()=>{const calls=[];const client=createPrinterActionClient('desktop',async(c,args)=>{calls.push([c,args]);return true;});assert.equal(await client.cancelProblemJob('Test',4),true);assert.deepEqual(calls,[['cancel_problem_printer_job',{printerName:'Test',jobId:4}]]);});
const render=s=>renderToStaticMarkup(createElement(PrinterDiagnosticsPanel,{name:'Test',snapshot:s,busy:false,refresh:async()=>{},changed:async()=>{}}));
test('UI normal mantém explicações técnicas recolhidas e não oferece plano manual',()=>{const html=render(snapshot());const main=html.slice(0,html.indexOf('<details'));assert.doesNotMatch(main,/comunicação física|Spooler|Driver|checkbox|select/);assert.match(html,/Comunicação física/);assert.match(html,/Não confirmada/);assert.match(html,/Detalhes técnicos/);assert.doesNotMatch(html,/Executar ações selecionadas|Plano de correção|checkbox|<details[^>]* open/);});
test('UI oferece verificação e proposta única de porta com confirmação separada',()=>{const s=snapshot();s.printer.statusBits=1;let html=render(s);assert.match(html.slice(0,html.indexOf('<details')),/Verificar e corrigir/);s.ports=col([port('COM4')]);s.serial=col([serial('COM4')]);s.presentDevices=devices(['COM4']);html=render(s);assert.match(html,/Corrigir porta/);assert.doesNotMatch(html.slice(0,html.indexOf('<details')),/select|Inventário|Reiniciar Spooler/);s.ports.items.push(port('COM5'));s.serial.items.push(serial('COM5'));s.presentDevices=devices(['COM4','COM5']);html=render(s);assert.doesNotMatch(html,/Corrigir porta/);});
